services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vete-admin
      - POSTGRES_DB=vetedb
      - POSTGRES_PASSWORD=securepassword1234!
    ports:
      - '5432:5432'
  adminer:
        image: adminer
        ports:
          - 8080:8080
        depends_on:
          - postgres
volumes:
  postgres-data:
    driver: local